{
  'name': 'Congatudo Nightly build',
  'on': {
    'schedule': [
      {
        'cron': '0 0 * * *'
      }
    ],
    'workflow_dispatch': null
  },
  'jobs':
    {
      'nightly_build':
        {
          'runs-on': 'ubuntu-latest',
          'if': "github.repository_owner == 'congatudo'",
          'steps':
            [
              { 
                'uses': 'actions/checkout@v3',
                'with': {
                  'fetch-depth': 0
                }
              },
              {
                'name': 'Use Node.js 18.x',
                'uses': 'actions/setup-node@v3',
                'with': { 'node-version': '18.x' },
              },
              { 'name': 'Install', 'run': 'npm ci' },
              {
                'name': 'Generate OpenAPI Docs',
                'run': 'npm run build_openapi_schema',
              },
              {
                'name': 'Build Congatudo frontend',
                'run': 'npm run build --workspace=frontend',
              },
              {
                'name': 'Build Congatudo',
                'run': 'npm run build --workspace=backend',
              },
              {
                'name': 'UPX-compress Congatudo binaries',
                'run': 'npm run upx',
              },
              {
                'name': 'Generate changelog',
                'run': 'npm run generate_nightly_changelog',
              },
              {
                'name': 'Build manifest',
                'run': 'npm run build_release_manifest nightly',
              },
              {
                'name': 'Push binaries to nightly repo',
                'id': 'push_directory',
                'uses': 'congatudo/github-action-push-to-another-repository@main',
                'env': {
                  'API_TOKEN_GITHUB': '${{ secrets.NIGHTLY_API_TOKEN_GITHUB }}'
                },
                'with': {
                  'source-directory': 'build',
                  'destination-github-username': 'congatudo-bot',
                  'destination-repository-name': 'congatudo-nightly',
                  'destination-repository-username': 'congatudo',
                  'user-email': 'congatudo@congatudo.cloud',
                  'target-branch': 'master'
                }
              }
            ],
        },
    },
}